### ISSUE TITLE
Add TypeScript interface

### ISSUE THREAD

**Issue by bradleyayers** [doesdev/pg-ears#3]
Are you open to having TypeScript definitions added to this package?

The implications are:

- If the API changes, the extra step of updating the TypeScript definition is required.
- Consumers don't need to install `@types/pg-ears` to get great TypeScript support.

If you're not comfortable with this, the definitions can be put in DefinitelyTyped (I have an open pull request pending your decision: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20152)

**Comment by doesdev** [comment]
I'm not a ts user myself, but if the following conditions are true then yeah I'm good with it.

- doesn't impose significant dev overhead / require (significant) additional dev tooling
- tests can be configured to fail if an API change breaks the TS definitions

**Comment by bradleyayers** [comment]
> tests can be configured to fail if an API change breaks the TS definitions

This isn't possible unless pg-ears was converted to TS (let me know if you're open to this). When manually writing types and storing them adjacent to a JS file, there's fundamentally no relationship between the two, and so a change in the JS is not checked against the TS, and vice-versa.

**Comment by doesdev** [comment]
Hmm, seems like someone (sh|w)ould make a module to fill this gap for testing side by side definitions. Anyway, in lieu of that I guess DefinitelyTyped is a good option. Thanks for the interest. If you come across / make such a module (or I get bored enough to do it) we can reopen this.

**Comment by bradleyayers** [comment]
I suspect in general the response to such a proposal would that it's better to just write the module in TypeScript so that:

1. the type assertions are co-located with the logic, and
2. you're able to both type check your own code while producing a standalone `.js` and `.d.ts` for consumers.

But I appreciate that not everyone wants to go down that route :smile:.
