### ISSUE TITLE
pg-ears vs idle_in_transaction_session_timeout

### ISSUE THREAD

**Issue by cschwaderer** [doesdev/pg-ears#5]
I'm using pg-ears with Postgres 11.

Recently, I had trouble on a test database cluster with pg-ears connections: There were far too many `LISTEN` queries and eventually, the cluster ran out of connections. (Luckily, this didn't happen so far on the production system.)
I don't know yet how this did happen and I don't know if it's pg-ears' fault or not.
Anyway, I'm thinking now about setting `idle_in_transaction_session_timeout` in the Postgres config. However, I'm not quite sure about the damage this will do to pg-ears. `LISTEN` queries of pg-ears are idle by design (so to say). So, any value for `idle_in_transaction_session_timeout` will kill pg-ears'  `LISTEN` queries eventually. 

- Will this cause any problems? Any side-effects? (Except bloating the logs with things like `error: terminating connection due to administrator command`)

- What would be a sensitive value for `idle_in_transaction_session_timeout`, balancing the need to prevent running out of connections vs forcing pg-ears to re-connect each time?

**Edit:** I am now quite sure that pg-ears is somehow responsible for this problem. See my other issue https://github.com/doesdev/pg-ears/issues/6

**Comment by doesdev** [comment]
I'm going to close this one in favor of leaving the other open for reference. Thanks for reporting these issues.
